# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    D14X79QZPNN3JG5NK2E8:
                        password: $2y$12$pHNU3JqqPYrv4gI.Hz1lIuvX5Wf0v0JBexXXY46H6Fnl/WQQz0X6m
                        roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            http_basic:
                realm: 'API area'
                provider: 'in_memory'
        main:
            anonymous: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/api/*, roles: ROLE_USER }